name: Other Release workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  
  first_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login to Github Packages
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Chainloop
        run: |
          curl -sfL https://docs.chainloop.dev/install.sh | bash -s

      - name: Install Syft
        run: |
          # Install Syft
          wget --no-verbose https://raw.githubusercontent.com/anchore/syft/c43f4fb416c34c1c4b3997373689d8d4c0fb9b36/install.sh -O - | sh -s -- -b /usr/local/bin

      - name: Run a one-line script
        run: |
          images=$(cat .github/workflows/artifact.json | jq -r '.[] | select(.type=="Docker Image" or .type=="Docker Manifest") | .path')
          for entry in $images; do
            # exclude latest tag
            if [[ $entry != *latest ]]; then
              # Extract only the image name and the architecture on the tag
              repo="${entry%:*}"                    # Remove tag
              repo="${repo##*/}"                    # Extract last segment after the last '/'
              material_name="${repo}-${entry##*-}"  # Construct final name


              syft -o cyclonedx-json=/tmp/sbom-$material_name.cyclonedx.json $entry
              ls -l /tmp

              # Material name is the name of the image
              echo "Material name: $material_name"
              # Tag is the tag of the image
              echo "Tag: $entry"
            fi
          done

