name: Other Release workflow

on:
  pull_request:

jobs:
  
  first_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login to Github Packages
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a one-line script
        run: |
          images=$(cat artifact.json | jq -r '.[] | select(.type=="Docker Image" or .type=="Docker Manifest") | .path')
          for entry in $images; do
            # exclude latest tag
            if [[ $entry != *latest ]]; then
              # Extract only the image name and the architecture on the tag
              repo="${entry%:*}"                    # Remove tag
              repo="${repo##*/}"                    # Extract last segment after the last '/'
              material_name="${repo}-${entry##*-}"  # Construct final name


              # Material name is the name of the image
              echo "Material name: $material_name"
              # Tag is the tag of the image
              echo "Tag: $entry"
            fi
          done

