name: Other Release workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  
  first_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login to Github Packages
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Chainloop
        run: |
          curl -sfL https://docs.chainloop.dev/install.sh | bash -s

      - name: Install Syft
        run: |
          # Install Syft
          wget --no-verbose https://raw.githubusercontent.com/anchore/syft/c43f4fb416c34c1c4b3997373689d8d4c0fb9b36/install.sh -O - | sh -s -- -b /usr/local/bin
      
      - name: Initialize Attestation
        run: |
          chainloop attestation init --workflow ${CHAINLOOP_WORKFLOW_NAME} --project ${CHAINLOOP_PROJECT_NAME}
        env:
          CHAINLOOP_TOKEN: ${{ secrets.CHAINLOOP_TOKEN }}
          CHAINLOOP_WORKFLOW_NAME: "release"
          CHAINLOOP_PROJECT_NAME: "core"

      - name: Run a one-line script
        env:
          CHAINLOOP_TOKEN: ${{ secrets.CHAINLOOP_TOKEN }}
        run: |
          images=$(cat .github/workflows/artifact.json | jq -r '.[] | select(.type=="Docker Image" or .type=="Docker Manifest") | .path')
          for entry in $images; do
            # exclude latest tag
            if [[ $entry != *latest ]]; then
              material_name="$(echo $entry | sed 's#.*/##')"

              syft -o cyclonedx-json=/tmp/sbom-$material_name.cyclonedx.json $entry
              ls -lh /tmp

              # Material name is the name of the image
              echo "Material name: $material_name"
              # Tag is the tag of the image
              echo "Tag: $entry"

              syft -o cyclonedx-json=/tmp/sbom-$material_name.cyclonedx.json $entry
              echo "chainloop attestation add --value $entry"
              chainloop --debug attestation add --value $entry
              echo "chainloop attestation add --value /tmp/sbom-$material_name.cyclonedx.json"
              chainloop --debug attestation add --value /tmp/sbom-$material_name.cyclonedx.json
            fi
          done

          chainloop attestation push

