name: Yet another release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  onboard_workflow:
    name: Onboard Chainloop Workflow
    uses: chainloop-dev/labs/.github/workflows/chainloop_github_release.yml@98dc5640cdf9573b91994350f126a355029456d7
    with:
      project: "chainloop"
      workflow_name: "chainloop-vault-release"
      additional_materials: "ghcr.io/chainloop-dev/chainloop/control-plane:${{ github.ref_name }},ghcr.io/chainloop-dev/chainloop/artifact-cas:${{ github.ref_name }},ghcr.io/chainloop-dev/chainloop/cli:${{ github.ref_name }}"
    secrets:
      api_token: ${{ secrets.CHAINLOOP_API_TOKEN }}
      cosign_key: ${{ secrets.COSIGN_KEY }}
      cosign_password: ${{ secrets.COSIGN_PASSWORD }}
